### PR TITLE
changed ugly filter buttons to pretty ones

### PR DESCRIPTION
**Pull request by alexkcode**

### CODE REVIEW

**Comment by briankung** [comment]
Can you make sure todo items match this?

- [ ] advanced/refactored search
- [ ] fix janky navbar
- [ ] paging / infinite scroll
- [ ] use webpack for assets
- [ ] undo
- [ ] filter + search

**Comment by alexkcode** [comment]
Done.

**Review by alexkcode — COMMENTED** [review]
added the To Do items as requested

**Review by briankung — APPROVED** [review]

**Comment by briankung** [comment]
Thanks! 👍

**Pull request merged**
